### ISSUE TITLE
Opened a Logistic_Normal branch

### ISSUE THREAD

**Issue by Craig44** [Casal2/CASAL2#167]
I have created a Logistic Normal branch to store the spec that I have made in. It is not ready to be integrated into the main repository for the following reasons;
- Likelihood/Children/Logistic_normal uses a lot of matrix manipulation calculating determinants, inverses, transposes etc. I have used the third party boost library to do deal with these matrix methods. The problem with this implementation is that the boost library cannot deal with Double a class which we use to convert doubles to variables that can be used by all the auto-diff libraries. It works fine for non-autodiff builds (release, debug). I implemented it to use for simulating compositional data which is fine as this uses non-autodiff builds. This needs to be resolved in the future for merging into the master

**Comment by Craig44** [comment]
The bigger issue with regards to this spec is we don't have access to a thirdparty library for BLAS (Basic Linear Algebra subprograms) or matrix manipulation which already is hindering our development and will continue to do so in the future. I believe we start by having access from boost to our auto-diff class Cppad first, and if we have the resources extend out to other auto-diff mini misers.

**Comment by Craig44** [comment]
I think that we can get around this, I have come across the file Source\Age\AgeingErrors\Children\Normal which uses boost but any double value it uses you need to wrap in a AS_DOUBLE(), Something to do would be to wrap the LogisticNormal Brance with all AS_DOUBLE's then we can use that likelihood for compositional data which would be quite cool

**Comment by Zaita** [comment]
AS_DOUBLE will break the auto-diff chain and cause undefined behaviour (or non-optimisation) in the autodiff minimiser.

You can wrap this class in the header with #IFDEFs to prevent it being accessible in auto-diff minimizers. The same way we manage the different minimizers in the minimizer factory.

As a permanent fix. I'd look at using matrix manipulations in the CppAD BLAS library as they use them for their own chain work. I'm not sure it'll work across multiple-autodiff methods. Otherwise we copy+paste+"enhance" the boost code as it's open source.

**Comment by Craig44** [comment]
I think we merge This likelihood into the master with non-autodiff statement. It would be useful to have this likelihood for simulating at the least, but can also be used for estimation during non-autodiff minimisers.

**Comment by Casal2** [comment]
Closing as branch has been merged.
